Repository FRONT-END-BOOTCAMP-PLUS-3/todo-hunter, pull requests merged in 2025-02, with the labels that each got.

#13 feat/#12 prisma schema 정의 1차
  prisma/schema.prisma
Labels: :sparkles: Feat

#21 feat/#17 필수 디렉토리 구성
  app/(auth)/index.ts
  app/api/route.ts
  app/play/character/page.tsx
  app/play/ending/page.tsx
  app/play/quest/page.tsx
  app/play/title/page.tsx
  app/play/tutorial/page.tsx
  application/usecases/index.ts
  components/common/index.ts
  constants/index.ts
  domain/entities/index.ts
  domain/repositories/index.ts
  infrastructure/repositories/index.ts
Labels: :wrench: Setting

#22 Feat/#20 공통 디자인 설계
  app/globals.css
  components/ui/input.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: 💄Design

#16 feat/#3 button 공통 컴포넌트 구현
  app/globals.css
  app/layout.tsx
  app/page.tsx
  components/ui/button.tsx
  package-lock.json
  package.json
Labels: :sparkles: Feat

#23 feat/#8 tag 공통 컴포넌트 구현
  .vscode/settings.json
  app/globals.css
  components/common/Tag.tsx
  components/common/index.ts
  constants/index.ts
  constants/status.ts
  package-lock.json
  package.json
  prisma/migrations/20250223095748_init/migration.sql
  prisma/migrations/migration_lock.toml
Labels: :sparkles: Feat

#31 Feat/#9 input 컴포넌트 리팩토링
  app/globals.css
  components/common/Button.tsx
  components/common/index.ts
  components/common/input.tsx
  components/ui/input.tsx
Labels: ♻️Refactor

#32 Feat/#5 sonner 컴포넌트 구현
  components/common/sonner.tsx
Labels: :sparkles: Feat

#14 feat/#7 navigation 컴포넌트 구현
  app/globals.css
  components/common/Navigation.tsx
  components/common/tabs.tsx
  constants/menu.ts
  package-lock.json
  package.json
  public/file.svg
  public/globe.svg
  public/images/border_round.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
Labels: :sparkles: Feat

#19 feat/#11 dialog 공통 컴포넌트 구현
  app/globals.css
  components/common/DialogButton.tsx
  components/common/dialog.tsx
  components/common/input.tsx
  components/common/label.tsx
  package-lock.json
  package.json
Labels: :sparkles: Feat

#33 Feat/#10 select 공통컴포넌트 구현
  app/globals.css
  components/common/Navigation.tsx
  components/common/Select.tsx
  components/common/index.ts
  package-lock.json
  package.json
Labels: :sparkles: Feat

#34 feat/#24 user orm 구현
  domain/repositories/index.ts
  domain/repositories/user-repository.ts
  infrastructure/repositories/index.ts
  infrastructure/repositories/pr-user-repository.ts
  package-lock.json
  package.json
Labels: :sparkles: Feat, :mailbox_with_mail: API

#36 Bugfix/#35 공통컴포넌트 경로, 파일명 수정
  app/page.tsx
  components/common/Dialog.tsx
  components/common/DialogButton.tsx
  components/common/Input.tsx
  components/common/Navigation.tsx
  components/common/Sonner.tsx
  components/common/label.tsx
  components/common/tabs.tsx
  package-lock.json
Labels: :bug: Bug, :wrench: Setting

#38 Bugfix/#35 공통컴포넌트 import문 수정 및 재병합
  components/common/index.ts
Labels: :bug: Bug, :wrench: Setting

#46 refactor/#44 user orm di 리팩토링 및 prisma.ts 생성
  domain/repositories/IUserRepository.ts
  domain/repositories/index.ts
  infrastructure/repositories/PriUserRepository.ts
  infrastructure/repositories/index.ts
  lib/prisma.ts
Labels: :sparkles: Feat, :mailbox_with_mail: API, ♻️Refactor

#40 feat/#27 status orm 구현
  domain/repositories/IStatusRepository.ts
  domain/repositories/index.ts
  infrastructure/repositories/PriStatusRepository.ts
  infrastructure/repositories/index.ts
Labels: :sparkles: Feat, :mailbox_with_mail: API

#47 Feat/#30 successday orm 구현
  domain/entities/index.ts
  domain/repositories/ISuccessDayRepository.ts
  domain/repositories/index.ts
  infrastructure/repositories/PriSuccessdayRepository.ts
  infrastructure/repositories/index.ts
  package-lock.json
Labels: :sparkles: Feat, :mailbox_with_mail: API, ♻️Refactor

#41 feat/#29 usertitle orm 구현
  domain/repositories/IUserTitleRepository.ts
  domain/repositories/index.ts
  infrastructure/repositories/PriUserTitleRepository.ts
  infrastructure/repositories/index.ts
Labels: :sparkles: Feat, :mailbox_with_mail: API

#42 Feat/#25 character orm 구현
  domain/repositories/ICharacterRepository.ts
  domain/repositories/index.ts
  infrastructure/repositories/PriCharacterRepository.ts
  infrastructure/repositories/index.ts
Labels: :sparkles: Feat, :mailbox_with_mail: API

#45 feat/#28 title orm 구현
  domain/repositories/ITitleRepository.ts
  domain/repositories/index.ts
  infrastructure/repositories/PriTitleRepository.ts
  infrastructure/repositories/index.ts
Labels: :sparkles: Feat, :mailbox_with_mail: API

#43 feat/#26 quest orm 레포지토리 구현
  domain/repositories/IQuestRepository.ts
  domain/repositories/index.ts
  infrastructure/repositories/PriQusetRepository.ts
  infrastructure/repositories/index.ts
Labels: :sparkles: Feat, :mailbox_with_mail: API

#49 feat/#48 usecase 디렉토리 구조 정의
  application/usecases/auth/dtos/index.ts
  application/usecases/buff-card/dtos/index.ts
  application/usecases/character/dtos/index.ts
  application/usecases/ending/dtos/index.ts
  application/usecases/quest/dtos/index.ts
  application/usecases/title/dtos/index.ts
Labels: :wrench: Setting, :sparkles: Feat

#57 feat/#56 prisma schema 정의 2차
  package-lock.json
  package.json
  prisma/schema.prisma
Labels: :wrench: Setting, :sparkles: Feat, :mailbox_with_mail: API

#60 refactor/#59 chareater endingState 추가 및 업데이트
  domain/repositories/ICharacterRepository.ts
  infrastructure/repositories/PriCharacterRepository.ts
Labels: ♻️Refactor

#63 feat/#62 prisma schema 3차 정의
  prisma/schema.prisma
Labels: :wrench: Setting, :mailbox_with_mail: API, ♻️Refactor

#61 feat/#51 캐릭터 유즈케이스, DTO 구현
  application/usecases/character/CharacterUsecase.ts
  application/usecases/character/dtos/CharacterDTO.ts
  application/usecases/character/dtos/index.ts
  domain/repositories/IQuestRepository.ts
  domain/repositories/ISuccessDayRepository.ts
  infrastructure/repositories/PriQusetRepository.ts
  infrastructure/repositories/PriSuccessdayRepository.ts
Labels: ♻️Refactor

#66 feat/#54 ending usecase 구현
  application/usecases/ending/EndingUsecase.ts
  application/usecases/ending/dtos/EndingDTO.ts
  application/usecases/ending/dtos/index.ts
  constants/ending.ts
  constants/enum.ts
  constants/index.ts
  public/endings/ending1.png
  public/endings/ending2.png
  public/endings/ending3.png
Labels: :sparkles: Feat, :mailbox_with_mail: API
