Repository FRONT-END-BOOTCAMP-PLUS-3/todo-hunter, pull requests merged in 2025-03, with the labels that each got.

#67 refactor/#65 navigation 각 버튼 비활성화 기능 추가
  components/common/Navigation.tsx
  constants/menu.ts
Labels: ♻️Refactor

#64 feat/#50 auth usecase 구현, redis 모듈 주입, nodemailer 모듈 주입
  application/usecases/auth/CheckExistEmailUsecase.ts
  application/usecases/auth/CheckExistLoginIdUsecase.ts
  application/usecases/auth/CheckVerifyCodeUsecase.ts
  application/usecases/auth/DeleteVerifyCodeUsecase.ts
  application/usecases/auth/FindLoginIdUsecase.ts
  application/usecases/auth/GenerateVerifyCodeUsecase.ts
  application/usecases/auth/SendEmailUsecase.ts
  application/usecases/auth/SignInUsecase.ts
  application/usecases/auth/SignUpUsecase.ts
  application/usecases/auth/VerifyPasswordUsecase.ts
  application/usecases/auth/dtos/CheckExistEmailDTO.ts
  application/usecases/auth/dtos/CheckExistLoginIdDTO.ts
  application/usecases/auth/dtos/SignInRequestDTO.ts
  application/usecases/auth/dtos/SignInResponseDTO.ts
  application/usecases/auth/dtos/SignUpDTO.ts
  application/usecases/auth/dtos/index.ts
  application/usecases/auth/errors/LoginError.ts
  domain/repositories/IUserRepository.ts
  domain/repositories/IVerificationRepository.ts
  infrastructure/databases/redis/server.ts
  infrastructure/repositories/PriUserRepository.ts
  infrastructure/repositories/RdVerificationRepository.ts
  package-lock.json
  package.json
  utils/sendEmailTemplate.ts
Labels: :sparkles: Feat, :mailbox_with_mail: API

#75 feat/#74 이미지 업로드
  public/endings/cyberpunk-street-background4.png
  public/endings/ending1.png
  public/endings/ending2.png
  public/endings/ending3.png
  public/endings/old-dark-castle-background2.png
  public/images/backgrounds/Mountain-dusk-background1.png
  public/images/backgrounds/cyberpunk-street-background4.png
  public/images/backgrounds/old-dark-castle-background2.png
  public/images/backgrounds/underwater-fantasy-background3.png
  public/images/characters/flying-bird/frame1.png
  public/images/characters/flying-bird/frame2.png
  public/images/characters/flying-bird/frame3.png
  public/images/characters/flying-bird/frame4.png
  public/images/characters/flying-bird/frame5.png
  public/images/characters/flying-bird/frame6.png
  public/images/characters/flying-bird/frame7.png
  public/images/characters/mushroom/0__0000_Layer-1.png
  public/images/characters/mushroom/0__0001_Layer-2.png
  public/images/characters/mushroom/0__0002_Layer-3.png
  public/images/characters/mushroom/0__0003_Layer-4.png
  public/images/characters/mushroom/0__0004_Layer-5.png
  public/images/characters/mushroom/0__0005_Layer-6.png
  public/images/characters/mushroom/0__0006_Layer-7.png
  public/images/characters/mushroom/0__0007_Layer-8.png
  public/images/characters/mushroom/0__0008_Layer-9.png
  public/images/characters/mushroom/0__0009_Layer-10.png
  public/images/characters/player/attack1.png
  public/images/characters/player/attack2.png
  public/images/characters/player/attack3.png
  public/images/characters/player/attack4.png
  public/images/characters/player/idle01.png
  public/images/characters/player/idle02.png
  public/images/characters/player/idle03.png
  public/images/characters/player/idle04.png
  public/images/characters/player/idle05.png
  public/images/characters/player/idle06.png
  public/images/characters/snake/_0000_Layer-1.png
  public/images/characters/snake/_0001_Layer-2.png
  public/images/characters/snake/_0002_Layer-3.png
  public/images/characters/snake/_0003_Layer-4.png
  public/images/characters/werewolf/werewolf-idle1.png
  public/images/characters/werewolf/werewolf-idle2.png
  public/images/characters/werewolf/werewolf-idle3.png
  public/images/characters/werewolf/werewolf-idle4.png
  public/images/characters/werewolf/werewolf-idle5.png
Labels: :sparkles: Feat, 💄Design

#68 Feat/#53 title usecase구현, title 이미지 추가
  application/usecases/title/UserTitleUsecase.ts
  application/usecases/title/dtos/UserTitleDTO.ts
  constants/title.ts
  public/titles/title_01.png
  public/titles/title_02.png
  public/titles/title_03.png
  public/titles/title_04.png
  public/titles/title_05.png
  public/titles/title_06.png
  public/titles/title_07.png
  public/titles/title_08.png
  public/titles/title_09.png
Labels: :sparkles: Feat

#69 feat/#52 quest usecase 구현
  application/usecases/character/CharacterUsecase.ts
  application/usecases/quest/CheckCompleteQuestUsecase.ts
  application/usecases/quest/CompleteQuestUsecase.ts
  application/usecases/quest/CreateQuestUsecase.ts
  application/usecases/quest/DeleteQuestUsecase.ts
  application/usecases/quest/GetDailyQuestUsecase.ts
  application/usecases/quest/GetWeeklyQuestUsecase.ts
  application/usecases/quest/dtos/CompleteQuestDTO.ts
  application/usecases/quest/dtos/CreateQuestDTO.ts
  application/usecases/quest/dtos/DeleteQuestDTO.ts
  application/usecases/quest/dtos/GetQuestDTO.ts
  application/usecases/quest/dtos/index.ts
  application/usecases/quest/errors/CompleteQuestError.ts
  domain/repositories/IQuestRepository.ts
  infrastructure/repositories/PriQusetRepository.ts
  package-lock.json
Labels: :sparkles: Feat

#79 feat/#71 ending 페이지 및 API 구현
  app/api/ending/route.ts
  app/globals.css
  app/play/ending/_components/EndingImage.tsx
  app/play/ending/_components/EndingScriptBox.tsx
  app/play/ending/_components/index.ts
  app/play/ending/page.tsx
  constants/ending.ts
Labels: :sparkles: Feat, :mailbox_with_mail: API

#77 Feat/#72 캐릭터 페이지 구현
  app/api/character/route.ts
  app/play/character/_components/character.css
  app/play/character/_components/status.tsx
  app/play/character/page.tsx
  application/usecases/character/dtos/CharacterDTO.ts
  application/usecases/character/dtos/index.ts
  public/images/backgrounds/Character-Page-Bg.png
Labels: :sparkles: Feat

#85 Feat/#70 quest api
  app/api/auth/me/route.ts
  app/api/auth/route.ts
  app/api/quest/[id]/route.ts
  app/api/quest/complete/route.ts
  app/api/quest/route.ts
  app/api/route.ts
  app/layout.tsx
  app/play/quest/add-quest/page.tsx
  app/play/quest/page.tsx
  application/usecases/quest/CompleteQuestUsecase.ts
  application/usecases/quest/CreateQuestUsecase.ts
  application/usecases/quest/DeleteQuestUsecase.ts
  application/usecases/quest/dtos/index.ts
  components/common/DateSelcetor.tsx
  components/common/Navigation.tsx
  components/common/OctagonX.tsx
  components/quest/DailyQuest.tsx
  components/quest/FightField.tsx
  components/quest/WeeklyQuest.tsx
  constants/menu.ts
  public/icons/Bolt.svg
  public/icons/Octagon_x.svg
  utils/auth.ts
Labels: :sparkles: Feat, 💄Design

#89 feat/#73 auth api 및 회원가입/로그인/아이디 찾기 기능 구현
  app/(auth)/findid/page.tsx
  app/(auth)/signin/page.tsx
  app/(auth)/signup/page.tsx
  app/api/auth/check-exist-email/route.ts
  app/api/auth/check-exist-login-id/route.ts
  app/api/auth/check-verify-code/route.ts
  app/api/auth/find-login-id/route.ts
  app/api/auth/send-signup-email/route.ts
  app/api/auth/signin/route.ts
  app/api/auth/signup/route.ts
  app/globals.css
  application/usecases/auth/CheckVerifyCodeUsecase.ts
  application/usecases/auth/FindLoginIdByEmailUsecase.ts
  application/usecases/auth/SendSignUpEmailUsecase.ts
  application/usecases/auth/SignInUsecase.ts
  application/usecases/auth/SignUpUsecase.ts
  application/usecases/auth/VerifyPasswordUsecase.ts
  application/usecases/auth/dtos/SignInResponseDTO.ts
  application/usecases/auth/dtos/SignUpRequestDTO.ts
  application/usecases/auth/errors/VerifyCodeError.ts
  components/auth/FindIdForm.tsx
  components/auth/FindIdView.tsx
  components/common/Input.tsx
  domain/repositories/IVerificationRepository.ts
  infrastructure/databases/redis/server.ts
  infrastructure/repositories/RdVerificationRepository.ts
  package-lock.json
  package.json
  utils/sendEmailTemplate.ts
Labels: :sparkles: Feat, :mailbox_with_mail: API

#83 Feat/#82 캐릭터 페이지, 캐릭터 모션 구현
  app/play/character/_components/character.css
  app/play/character/_components/character.tsx
  app/play/character/_components/status.tsx
  app/play/character/page.tsx
Labels: :sparkles: Feat

#81 Feat/#78 칭호 페이지 구현
  app/api/title/route.ts
  app/play/title/_components/renderTitleItem.tsx
  app/play/title/page.tsx
  application/usecases/title/UserTitleUsecase.ts
  application/usecases/title/dtos/RenderTitleDTO.ts
  application/usecases/title/dtos/index.ts
  domain/repositories/IUserTitleRepository.ts
  infrastructure/repositories/PriUserTitleRepository.ts
  public/titles/title_df.png
Labels: :sparkles: Feat

#91 feat/#80 node-cron 구현 및 스케줄링 추가
  ecosystem.config.cjs
  lib/crons/cron-type.ts
  lib/crons/ending-close-cron.ts
  lib/crons/ending-open-cron.ts
  lib/crons/index.ts
  lib/crons/status-reset-cron.ts
  lib/crons/test-log-cron.ts
  lib/crons/worker.ts
  package-lock.json
  package.json
Labels: :wrench: Setting, :sparkles: Feat, :mailbox_with_mail: API

#93 Feat/#87 zustand, 유저데이터 관리
  app/page.tsx
  app/play/character/page.tsx
  utils/stores/characterStore.ts
Labels: :sparkles: Feat

#92 feat/#88 quest 페이지 zustand 전역 상태 관리
  app/api/quest/[id]/route.ts
  app/api/quest/complete/route.ts
  app/api/quest/route.ts
  app/play/quest/add-quest/page.tsx
  app/play/quest/page.tsx
  components/common/DateSelector.tsx
  components/quest/DailyQuest.tsx
  components/quest/WeeklyQuest.tsx
  utils/stores/questStore.ts
  utils/stores/useQuestFormStore.ts
Labels: :bug: Bug, :mailbox_with_mail: API, ♻️Refactor

#101 refactory/#98 zustand로 캐릭터 데이터 관리
  app/play/character/page.tsx
Labels: ♻️Refactor

#95 Feat/#84 이미지+state 상태관리를 통한 애니메이션 처리 모션
  app/globals.css
  app/layout.tsx
  app/play/quest/add-quest/page.tsx
  app/play/quest/page.tsx
  components/quest/CharactersMotion.tsx
  components/quest/DailyQuest.tsx
  components/quest/FightField.tsx
  components/quest/WeeklyQuest.tsx
  components/quest/testCharacterM.tsx
  utils/stores/questStore.ts
  utils/stores/useProgressStore.ts
  utils/stores/useQuestFormStore.ts
Labels: :sparkles: Feat

#96 Feat/#94 전역 레이아웃 설정
  app/layout.tsx
  app/play/character/_components/character.css
  app/play/character/_components/status.tsx
  app/play/character/page.tsx
  app/play/quest/page.tsx
  app/play/title/page.tsx
  components/quest/DailyQuest.tsx
  components/quest/WeeklyQuest.tsx
Labels: 💄Design

#105 fix/#104 Navigation 컴포넌트 중앙 버튼 클릭시 하얀색 사각 배경 수정
  components/common/Navigation.tsx
Labels: :bug: Bug

#103 feat/#90 Auth 인증 미들웨어 구현, 액세스 토큰/리프레시 토큰 로드, 유저 인증관련 정보 zustand 상태관리
  app/(auth)/signin/page.tsx
  app/(auth)/signup/page.tsx
  app/api/auth/refresh/route.ts
  app/api/auth/route.ts
  app/api/auth/signin-info/route.ts
  app/api/auth/signin/route.ts
  app/api/auth/signup/route.ts
  app/api/character/route.ts
  application/usecases/auth/GenerateAccessTokenUsecase.ts
  application/usecases/auth/GenerateRefreshTokenUsecase.ts
  application/usecases/auth/RenewAccessTokenUsecase.ts
  application/usecases/auth/RenewRefreshTokenUsecase.ts
  application/usecases/auth/SignInUsecase.ts
  application/usecases/auth/SignUpUsecase.ts
  application/usecases/auth/VerifyAccessTokenUsecase.ts
  application/usecases/auth/VerifyRefreshTokenUsecase.ts
  application/usecases/auth/dtos/SignInResponseDTO.ts
  application/usecases/character/CharacterUsecase.ts
  application/usecases/character/dtos/CharacterDTO.ts
  domain/repositories/IRdAuthenticationRepository.ts
  infrastructure/databases/redis/server.ts
  infrastructure/repositories/RdAuthenticationRepository.ts
  middleware.ts
  package-lock.json
  package.json
  tailwind.config.ts
  utils/auth.ts
  utils/stores/userStore.ts
Labels: :sparkles: Feat, :mailbox_with_mail: API

#114 Hotfix/#113 build error
  app/(auth)/signin/page.tsx
  app/api/quest/[id]/route.ts
  app/api/quest/route.ts
  app/layout.tsx
  app/play/character/page.tsx
  app/play/quest/page.tsx
  app/play/title/page.tsx
  application/usecases/character/CharacterUsecase.ts
  application/usecases/title/UserTitleUsecase.ts
  components/quest/DailyQuest.tsx
  components/quest/FightField.tsx
  components/quest/WeeklyQuest.tsx
  package.json
  utils/stores/characterStore.ts
  utils/stores/questStore.ts
Labels: 🚑!HotFix

#116 feat/#102 deploy yml 작성
  .github/workflows/deploy.yml
Labels: :wrench: Setting, :rocket: Deploy

#100 Feat/#97 PWA 구현, 설치 유도 팝업
  app/head.tsx
  app/layout.tsx
  components/installPrompt/InstallPrompt.tsx
  global.d.ts
  next.config.ts
  public/icons/120.png
  public/icons/144.png
  public/icons/16.png
  public/icons/180.png
  public/icons/192.png
  public/icons/32.png
  public/icons/48.png
  public/icons/512.png
  public/icons/72.png
  public/icons/96.png
  public/manifest.json
  public/service-worker.js
  tsconfig.json
Labels: :sparkles: Feat

#120 Hotfix/#115 build error 해결
  app/api/auth/refresh/route.ts
  app/api/quest/[id]/route.ts
  app/api/quest/complete/route.ts
  app/api/quest/route.ts
  app/error.tsx
  app/globals.css
  app/play/quest/add-quest/page.tsx
  app/play/quest/page.tsx
  app/play/title/page.tsx
  app/play/tutorial/page.tsx
  application/usecases/auth/SignUpUsecase.ts
  components/common/Landing.tsx
  components/common/Select.tsx
  components/quest/CharactersMotion.tsx
  components/quest/testCharacterM.tsx
  ecosystem.config.cjs
  lib/crons/cron-type.ts
  lib/crons/ending-close-cron.ts
  lib/crons/ending-open-cron.ts
  lib/crons/index.ts
  lib/crons/status-reset-cron.ts
  lib/crons/test-log-cron.ts
  lib/crons/worker.ts
  package.json
  public/fonts/Galmuri9.woff2
  utils/auth.ts
Labels: :bug: Bug, 🚑!HotFix

#119 hotfix/#118 회원가입 시 인증메일 발송 후 이메일 주소 수정 구현
  app/(auth)/signup/page.tsx
Labels: 🚑!HotFix

#123 fix/#122 소개 페이지 버그 수정
  app/beginning/page.tsx
  app/globals.css
Labels: :bug: Bug

#127 fix/#124 칭호도감 이미지 표시불가 및 화면잘림 문제 수정
  app/play/title/_components/renderTitleItem.tsx
  app/play/title/page.tsx
  middleware.ts
Labels: :bug: Bug

#130 fix/#128 PWA 앱 다운로드 안내 모달 창 position 수정
  components/installPrompt/InstallPrompt.tsx
Labels: :bug: Bug

#133 fix/#131 퀘스트 및 캐릭터 페이지 CSS 동작 이상 문제 수정
  app/play/character/_components/character.css
  app/play/character/page.tsx
  app/play/quest/add-quest/page.tsx
  app/play/quest/page.tsx
  components/quest/DailyQuest.tsx
  components/quest/WeeklyQuest.tsx
Labels: :bug: Bug

#134 !Hotfix/#126 캐릭터 페이지 progress, status refetch로 실시간 반영 기능 구현
  app/play/character/page.tsx
  application/usecases/character/CharacterUsecase.ts
  application/usecases/quest/CompleteQuestUsecase.ts
  application/usecases/quest/GetWeeklyQuestUsecase.ts
  domain/repositories/IQuestRepository.ts
  domain/repositories/ISuccessDayRepository.ts
  infrastructure/repositories/PriQusetRepository.ts
  infrastructure/repositories/PriSuccessdayRepository.ts
  utils/stores/questStore.ts
Labels: :bug: Bug, 🚑!HotFix

#136 feat/#135 로그아웃 기능 구현
  app/api/auth/signout/route.ts
  app/play/character/page.tsx
Labels: :sparkles: Feat

#139 [2차 배포] develop 브랜치 -> main 브랜치 병합
  .github/workflows/deploy.yml
  app/api/auth/signout/route.ts
  app/beginning/page.tsx
  app/globals.css
  app/play/character/_components/character.css
  app/play/character/page.tsx
  app/play/ending/page.tsx
  app/play/quest/add-quest/page.tsx
  app/play/quest/page.tsx
  app/play/title/_components/renderTitleItem.tsx
  app/play/title/page.tsx
  application/usecases/character/CharacterUsecase.ts
  application/usecases/ending/EndingUsecase.ts
  application/usecases/quest/CompleteQuestUsecase.ts
  application/usecases/quest/GetWeeklyQuestUsecase.ts
  components/common/Navigation.tsx
  components/installPrompt/InstallPrompt.tsx
  components/quest/DailyQuest.tsx
  components/quest/WeeklyQuest.tsx
  domain/repositories/IQuestRepository.ts
  domain/repositories/ISuccessDayRepository.ts
  infrastructure/repositories/PriQusetRepository.ts
  infrastructure/repositories/PriSuccessdayRepository.ts
  middleware.ts
  utils/stores/questStore.ts
Labels: :rocket: Deploy

#146 fix/#145 로그인 API에 zustand userStore의 fetchUser 호출 추가
  app/(auth)/signin/page.tsx
  app/(auth)/signup/page.tsx
  app/api/auth/signup/route.ts
  app/play/character/page.tsx
Labels: :bug: Bug

#147 feat/#142 workflow yml ci test 단계 추가
  .github/workflows/deploy.yml
  package.json
Labels: :wrench: Setting, :mailbox_with_mail: API, :rocket: Deploy

#151 fix/#150 import 추가
  app/play/character/page.tsx
Labels: 🚑!HotFix

#155 hotfix/#154 questStore에 캐릭터 데이터 fetch하도록 수정
  utils/stores/questStore.ts
Labels: :bug: Bug, 🚑!HotFix
